name: portfolio
version: 1.0.0+1
publish_to: none
description: Portfolio developed in flutter.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  animated_glitch: ^1.1.1
  auto_size_text: ^3.0.0
  build_runner: ^2.4.5
  collection: ^1.17.1
  envied: ^0.3.0+3
  firebase_core: ^2.14.0
  flex_color_scheme: ^7.1.2
  flutter: 
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations: 
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_test: 
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  intl: ^0.18.0
  riverpod_annotation: ^2.1.1
  seo: ^0.0.4
  url_launcher: ^6.1.11
  url_strategy: ^0.2.0

dev_dependencies: 
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter: 
  assets: 
    - assets/images/
    - assets/projects/
  uses-material-design: true
  generate: true
